package view;

import controller.Partida;
import controller.Partida.Estado;
import dao.DAO;
import java.util.List;
import main.Decorador;
import main.Main;
import model.disparador.Nave;
import model.Precios;
import model.Precios.Precio;

/**
 *
 * @author chema
 */
public class Tienda extends javax.swing.JDialog {

    private DAO dao;
    private Decorador decorador;
    private Partida partida;
    private List<Nave> naves;
    private Nave naveSelec;
    private int numNaves;
    
    public Tienda(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        initComponents2();
    }
    
    private void initComponents2(){
        //Cargamos el objeto DAO para interacturar con la DB
        dao = DAO.getInstance(lblInfo);
        //Cargamos todos los movimientos
//        cbMovimientos.setModel(dao.selectAllMovimientos());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNaves = new javax.swing.ButtonGroup();
        jPanelTienda = new javax.swing.JPanel();
        rbNave1 = new javax.swing.JRadioButton();
        rbNave2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDineroDisponible = new javax.swing.JLabel();
        panelMejoras = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFuerza = new javax.swing.JLabel();
        lblResistencia = new javax.swing.JLabel();
        lblVidas = new javax.swing.JLabel();
        btComprarFuerza = new javax.swing.JButton();
        btComprarResistencia = new javax.swing.JButton();
        btComprarVidas = new javax.swing.JButton();
        lblPrecioFuerza = new javax.swing.JLabel();
        lblPrecioResistencia = new javax.swing.JLabel();
        lblPrecioVidas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMunicion = new javax.swing.JLabel();
        btComprarMunicion = new javax.swing.JButton();
        lblPrecioMunicion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        bgNaves.add(rbNave1);
        rbNave1.setSelected(true);
        rbNave1.setText("Nave: (1)");
        rbNave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNave1ActionPerformed(evt);
            }
        });

        bgNaves.add(rbNave2);
        rbNave2.setText("Nave: (2)");
        rbNave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNave2ActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Quién quiere mejoras?");

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tienda de mejoras");

        jLabel3.setText("Puntos disponibles:");

        lblDineroDisponible.setText("(puntos_disponibles)");

        jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel4.setText("Fuerza:");

        jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel5.setText("Resistencia total:");

        jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel6.setText("Vidas:");

        lblFuerza.setText("fuerza_");

        lblResistencia.setText("resistencia_");

        lblVidas.setText("vidas_");

        btComprarFuerza.setText("Comprar + 1");
        btComprarFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarFuerzaActionPerformed(evt);
            }
        });

        btComprarResistencia.setText("Comprar + 1");
        btComprarResistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarResistenciaActionPerformed(evt);
            }
        });

        btComprarVidas.setText("Comprar + 1");
        btComprarVidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarVidasActionPerformed(evt);
            }
        });

        lblPrecioFuerza.setText("(precio compra)");

        lblPrecioResistencia.setText("(precio compra)");

        lblPrecioVidas.setText("(precio compra)");

        jLabel7.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel7.setText("Munición:");

        lblMunicion.setText("munición_");

        btComprarMunicion.setText("Comprar + 1");
        btComprarMunicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarMunicionActionPerformed(evt);
            }
        });

        lblPrecioMunicion.setText("(precio compra)");

        jLabel9.setText("Actual:");

        jLabel8.setText("(necesarios)");

        lblInfo.setText("...");

        javax.swing.GroupLayout panelMejorasLayout = new javax.swing.GroupLayout(panelMejoras);
        panelMejoras.setLayout(panelMejorasLayout);
        panelMejorasLayout.setHorizontalGroup(
            panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMejorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMejorasLayout.createSequentialGroup()
                        .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMejorasLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResistencia)
                            .addComponent(lblVidas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMunicion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btComprarFuerza)
                            .addComponent(btComprarResistencia)
                            .addComponent(btComprarVidas)
                            .addComponent(btComprarMunicion))
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblPrecioFuerza)
                            .addComponent(lblPrecioResistencia)
                            .addComponent(lblPrecioVidas)
                            .addComponent(lblPrecioMunicion))
                        .addGap(30, 30, 30))
                    .addGroup(panelMejorasLayout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelMejorasLayout.setVerticalGroup(
            panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMejorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFuerza)
                    .addComponent(btComprarFuerza)
                    .addComponent(lblPrecioFuerza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblResistencia)
                    .addComponent(btComprarResistencia)
                    .addComponent(lblPrecioResistencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblVidas)
                    .addComponent(btComprarVidas)
                    .addComponent(lblPrecioVidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMejorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblMunicion)
                    .addComponent(btComprarMunicion)
                    .addComponent(lblPrecioMunicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblInfo))
        );

        btCerrar.setText("Cerrar");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTiendaLayout = new javax.swing.GroupLayout(jPanelTienda);
        jPanelTienda.setLayout(jPanelTiendaLayout);
        jPanelTiendaLayout.setHorizontalGroup(
            jPanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTiendaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(rbNave2)
                    .addComponent(rbNave1)
                    .addGroup(jPanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btCerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDineroDisponible, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMejoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTiendaLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTiendaLayout.setVerticalGroup(
            jPanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTiendaLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelTiendaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(rbNave1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNave2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDineroDisponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCerrar))
                    .addComponent(panelMejoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
        actNumNaves();        
    }//GEN-LAST:event_formComponentShown
           
    private void rbNave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNave2ActionPerformed
        naveSelec = naves.get(1);
        cargarDatos(naveSelec);
    }//GEN-LAST:event_rbNave2ActionPerformed

    private void rbNave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNave1ActionPerformed
        naveSelec = naves.get(0);
        cargarDatos(naveSelec);
    }//GEN-LAST:event_rbNave1ActionPerformed

    private void btComprarFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarFuerzaActionPerformed
        Precio precioAMejorar = naveSelec.getPrecios().getFuerza();
        comprar(precioAMejorar);
    }//GEN-LAST:event_btComprarFuerzaActionPerformed

    private void btComprarResistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarResistenciaActionPerformed
        Precio precioAMejorar = naveSelec.getPrecios().getResistencia();
        comprar(precioAMejorar);
    }//GEN-LAST:event_btComprarResistenciaActionPerformed

    private void btComprarVidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarVidasActionPerformed
        Precio precioAMejorar = naveSelec.getPrecios().getVidas();
        comprar(precioAMejorar);
    }//GEN-LAST:event_btComprarVidasActionPerformed

    private void btComprarMunicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarMunicionActionPerformed
        Precio precioAMejorar = naveSelec.getPrecios().getMunicion();
        comprar(precioAMejorar);
    }//GEN-LAST:event_btComprarMunicionActionPerformed
    
    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        this.setVisible(false);
        //partida.setEstado(Estado.JUGANDO);
    }//GEN-LAST:event_btCerrarActionPerformed

    /**
     * Inicializamos todas los miembros
     */
    private void init(){
        decorador = ((Main)getParent()).getDecorador();
        partida = decorador.getPartida();
        naves = partida.getNaves();
        numNaves = naves.size();
        naveSelec = naves.get(0);
        cargarDatos(naveSelec);
    }
    
    /**
     * Comprueba el número de naves que existen en la partida
     */
     private void actNumNaves(){
        //Nombres de las naves
        Nave nave = naves.get(0);
        rbNave1.setText(nave.getNombre());
        nave = naves.get(1);
        rbNave2.setText(nave.getNombre());
        
        if(numNaves==1) rbNave2.setEnabled(false);
        else rbNave2.setEnabled(true);
    }   
    
    /**
     * Cargamos todos los datos de la nave pasada por parámetro
     * @param nave nave a cargar 
     */
    private void cargarDatos(Nave nave){
        lblInfo.setText("");
        Precios precios = nave.getPrecios();
        
        String puntos = ""+nave.getPuntos(),
                resistencia = ""+nave.getSaludTotal(),
                vidas = ""+nave.getVidas(),
                fuerza = ""+nave.getFuerza(),
                muni = ""+nave.getMunicionMax();
        String pResistencia = "", pVidas = "",pFuerza= "",pMuni= "";        
        pResistencia = ""+precios.getResistencia().getActual();
        pVidas = ""+precios.getVidas().getActual();
        pFuerza = ""+precios.getFuerza().getActual();
        pMuni = ""+precios.getMunicion().getActual();
        
        lblDineroDisponible.setText(puntos);
        
        lblFuerza.setText(fuerza);
        lblResistencia.setText(resistencia);
        lblVidas.setText(vidas);
        lblMunicion.setText(muni);
       
        lblPrecioMunicion.setText(format(pMuni));
        lblPrecioFuerza.setText(format(pFuerza));
        lblPrecioResistencia.setText(format(pResistencia));
        lblPrecioVidas.setText(format(pVidas));
    }
    
    /**
     * Dar formato a la salida de texto de los precios
     * @param s
     * @return s + "puntos"
     */
    private String format(String s){
        s += " puntos";
        return s;
    }
    
    /**
     * Comprar mejora
     * @param precioAMejorar 
     */
    private void comprar(Precio precioAMejorar){        
        boolean huboCompra = naveSelec.comprar(precioAMejorar); 
        if(huboCompra){
            cargarDatos(naveSelec);
            dao.update(precioAMejorar);
        }
    }
    
    
    //<editor-fold defaultstate="collapsed" desc="Variables declaration - do not modify">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgNaves;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btComprarFuerza;
    private javax.swing.JButton btComprarMunicion;
    private javax.swing.JButton btComprarResistencia;
    private javax.swing.JButton btComprarVidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelTienda;
    private javax.swing.JLabel lblDineroDisponible;
    private javax.swing.JLabel lblFuerza;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblMunicion;
    private javax.swing.JLabel lblPrecioFuerza;
    private javax.swing.JLabel lblPrecioMunicion;
    private javax.swing.JLabel lblPrecioResistencia;
    private javax.swing.JLabel lblPrecioVidas;
    private javax.swing.JLabel lblResistencia;
    private javax.swing.JLabel lblVidas;
    private javax.swing.JPanel panelMejoras;
    private javax.swing.JRadioButton rbNave1;
    private javax.swing.JRadioButton rbNave2;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
